name: make_docs

on:
  # Trigger the workflow on push or pull request, for develop branch
  push:
    branches:
      - master
      - develop      
  pull_request:
    branches:
      - develop

jobs:      
  make_mkdocs:
    name: Build mkdocs
    runs-on: ubuntu-latest
    needs: merge_to_docs
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}    
    - uses: actions/checkout@v2
      with:
        ref: develop #checkout at docs branch          
    - name: update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install python dependencies
      uses: ./.github/actions/install-requirements
      with:
        path: requirements/docs_requirements.txt
    - name: Deploy documentation
      env:
        GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
      run: |
        mkdocs gh-deploy --force
        mkdocs --version
